---
- name: ensure required PostgreSQL locales are present
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ dubzland_postgres_locales }}"
  notify: restart postgres

- name: ensure PostgreSQL global configuration is present
  lineinfile:
    dest: "{{ dubzland_postgres_configuration_directory }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ dubzland_postgres_configuration }}"
  notify: restart postgres

- name: ensure PostgreSQL host based authentication is configured
  template:
    src: "etc/postgresql/pg_hba.conf.j2"
    dest: "{{ dubzland_postgres_configuration_directory }}/pg_hba.conf"
    owner: "{{ dubzland_postgres_user }}"
    group: "{{ dubzland_postgres_group }}"
    mode: 0600
  notify: restart postgres
  when: dubzland_postgres_hba_entries | length > 0

- name: ensure unix socket directories exist for PostgreSQL
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ dubzland_postgres_user }}"
    group: "{{ dubzland_postgres_group }}"
    mode: 02775
  with_items: "{{ dubzland_postgres_socket_directories }}"
  notify: restart postgres
