---
- name: ensure PostgreSQL is configured
  lineinfile:
    dest: "{{ dubzland_postgres_configuration_directory }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ dubzland_postgres_configuration }}"
  notify: restart postgres

- name: ensure unix socket directories exist for PostgreSQL
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ dubzland_postgres_user }}"
    group: "{{ dubzland_postgres_group }}"
    mode: 02775
  with_items: "{{ dubzland_postgres_socket_directories }}"
  notify: restart postgres
