---
- name: ensure PostgreSQL databases are present
  postgresql_db:
    encoding: "{{ item.encoding | default('UTF-8') }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(dubzland_postgres_socket_directories | first) }}"
    login_user: "{{ item.login_user | default(dubzland_postgres_user) }}"
    name: "{{ item.name }}"
    owner: "{{ item.owner | default(dubzland_postgres_user) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    template: "{{ item.template | default('template0') }}"
  with_items: "{{ dubzland_postgres_databases }}"
  no_log: True
  become: True
  become_user: "{{ dubzland_postgres_user }}"
