---
- name: ensure extensions are configured for PostgreSQL databases
  postgresql_ext:
    db: "{{ item.db }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(dubzland_postgres_socket_directories | first) }}"
    login_user: "{{ item.login_user | default(dubzland_postgres_user) }}"
    name: "{{ item.name }}"
    port: "{{ item.port | default(omit) }}"
    schema: "{{ item.schema | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ dubzland_postgres_extensions }}"
  become: True
  become_user: "{{ dubzland_postgres_user }}"
