---
- include_tasks: variables.yml
- include_tasks: packages.yml
- include_tasks: configuration.yml

- name: dump the service name
  debug:
    msg: "{{ dubzland_postgres_service_name }}"

- name: dump the journal
  command: journalctl --no-pager
  register: journal_dump1

- name: show the journal
  debug:
    msg: "{{ journal_dump1.stdout_lines }}"

- name: try to start postgres
  shell: timeout 1m systemctl restart postgres@11-main
  register: restart_logs

- name: dump the restart log
  debug:
    msg: "{{ restart_logs.stdout_lines }}"

- meta: flush_handlers

# - name: ensure PostgreSQL is running
#   systemd:
#     name: "{{ dubzland_postgres_service_name }}"
#     state: started

- name: try to start postgres
  systemd:
    name: "{{ dubzland_postgres_service_name }}"
    state: started
    no_block: true
