---
- include_tasks: variables.yml
- include_tasks: packages.yml
- include_tasks: configuration.yml

- meta: flush_handlers

- name: ensure PostgreSQL is running
  service:
    name: "{{ dubzland_postgres_service_name }}"
    state: started
