---
- include_tasks: variables.yml
- include_tasks: packages.yml
- include_tasks: configuration.yml

- meta: flush_handlers

- name: ensure PostgreSQL is running
  service:
    name: "{{ dubzland_postgres_service_name }}"
    state: started
  when: not dubzland_postgres_client_only

- include_tasks: users.yml
  when: not dubzland_postgres_client_only

- include_tasks: databases.yml
  when: not dubzland_postgres_client_only

- include_tasks: extensions.yml
  when: not dubzland_postgres_client_only
