---
- include_tasks: variables.yml
- include_tasks: packages.yml

- meta: flush_handlers

- name: ensure PostgreSQL is running
  service:
    name: "{{ dubzland_postgres_service_name }}"
    state: started
    async: 100
    poll: 0
    register: service_sleeper

- name: check on service
  async_status:
    jid: "{{ service_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: dump job result
  debug:
    msg: "{{ job_result.stdout_lines + job_result.stderr_lines}}"
