---
- name: ensure gnupg is available for apt_key
  apt:
    name: gnupg
    state: present
  tags:
    - postgres

- name: ensure the PostgreSQL repository key is present
  apt_key:
    url: "{{ dubzland_postgres_repo_key_url }}"
    state: present
  tags:
    - postgres

- name: assign the PostgreSQL repository
  set_fact:
    dubzland_postgres_repository: "deb {{ dubzland_postgres_repo_url }} {{ ansible_lsb['codename'] }}-pgdg main"

- name: ensure the PostgreSQL repository is available
  apt_repository:
    repo: "{{ dubzland_postgres_repository }}"
    state: present
    update_cache: true
  tags:
    - postgres

- name: prepare PostgreSQL package names
  set_fact:
    dubzland_postgres_package_name_versioned: "{{ dubzland_postgres_package_name }}-{{ dubzland_postgres_version }}"
    dubzland_postgres_contrib_package_name_versioned: "{{ dubzland_postgres_contrib_package_name }}-{{ dubzland_postgres_version }}"
  when: dubzland_postgres_version | length > 0
  tags:
    - postgres

- name: prepare PostgreSQL base package list
  set_fact:
    dubzland_postgres_base_packages:
      - "{{ dubzland_postgres_package_name_versioned | default(dubzland_postgres_package_name) }}"
      - "{{ dubzland_postgres_contrib_package_name_versioned | default(dubzland_postgres_contrib_package_name) }}"

- name: prepare PostgreSQL package list
  set_fact:
    dubzland_postgres_packages: "{{ dubzland_postgres_base_packages + dubzland_postgres_extra_packages }}"
