---
- name: set os-specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars"

- when: ansible_os_family == 'Debian'
  block:
    - name: prepare PostgreSQL package names
      set_fact:
        dubzland_postgres_package_name_versioned: "{{ dubzland_postgres_package_name }}-{{ dubzland_postgres_version }}"
        dubzland_postgres_client_package_name_versioned: "{{ dubzland_postgres_client_package_name }}-{{ dubzland_postgres_version }}"
        dubzland_postgres_contrib_package_name_versioned: "{{ dubzland_postgres_contrib_package_name }}-{{ dubzland_postgres_version }}"
      tags:
        - postgres

    - when: dubzland_postgres_client_only
      block:
        - name: prepare PostgreSQL base package list
          set_fact:
            dubzland_postgres_base_packages:
              - "{{ dubzland_postgres_client_package_name_versioned }}"

    - when: not dubzland_postgres_client_only
      block:
        - name: prepare PostgreSQL base package list
          set_fact:
            dubzland_postgres_base_packages:
              - "{{ dubzland_postgres_package_name_versioned }}"
              - "{{ dubzland_postgres_contrib_package_name_versioned }}"

    - name: prepare PostgreSQL package list
      set_fact:
        dubzland_postgres_packages: "{{ dubzland_postgres_base_packages + dubzland_postgres_extra_packages }}"
