---
- name: enable postgres
  service:
    name: "{{ dubzland_postgres_service_name }}"
    enabled: True

- name: restart postgres
  service:
    name: "{{ dubzland_postgres_service_name }}"
    state: restarted
