---
dubzland_postgres_extra_packages: []
dubzland_postgres_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
dubzland_postgres_service_name: postgresql
dubzland_postgres_unix_socket_directories:
  - /var/run/postgresql
