---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-postgres
      vars:
        dubzland_postgres_users:
          - name: testuser
            password: testpassword
            encrypted: True
        dubzland_postgres_databases:
          - name: 'testdb'
            state: present
        dubzland_postgres_tables:
          - name: 'testtable'
            db: 'testdb'
            columns:
              - id bigserial primary key
              - name text
              - age bigint
            privileges:
              - user: testuser
                privs:
                  - SELECT
            state: present
