---
- name: Converge
  hosts: all
  roles:
    - role: dubzland-postgres
      vars:
        dubzland_postgres_users:
          - name: "testuser"
            password: "testpassword"
            encrypted: True
            role_attr_flags: "CREATEDB"
