---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-postgres
      vars:
        dubzland_postgres_databases:
          - name: 'testdb'
            state: present
        dubzland_postgres_extensions:
          - name: pg_trgm
            db: template1
            state: present
